import React from "react";
import dynamic from "next/dynamic";

import "swagger-ui-react/swagger-ui.css";

const SwaggerUI = dynamic(import("swagger-ui-react"), { ssr: false }); // Renders UI for generated Swagger Spec

// example https://github.com/jellydn/next-swagger-doc/tree/main/examples/example
export default function ApiDoc({ spec }) {
  return <SwaggerUI url="/api/swagger" />; // Swagger Spec is generated by /api/swagger API route
}
